/*
 **********************************************************************************************************************
 *
 * COPYRIGHT RESERVED, Robert Bosch GmbH, 2019. All rights reserved.
 * The reproduction, distribution and utilization of this document as well as the communication of its contents to
 * others without explicit authorization is prohibited. Offenders will be held liable for the payment of damages.
 * All rights reserved in the event of the grant of a patent, utility model or design.
 *
 **********************************************************************************************************************
 
 **********************************************************************************************************************
 Machine Type: MCU_RB_ST
 Generated by ICE 2.10.0  
 **********************************************************************************************************************
*/ 
#define MEMMAP_ERROR
/* MR12 RULE 4.10, 20.5 VIOLATION:  4.10: Memmap file must be included multiple times,  20.5: AUTOSAR MemMap concept requires #undef, AUTOSAR MemMap requirements are incompatible to MISRA */
#if defined CRC_START_SEC_CODE
  #undef CRC_START_SEC_CODE
  #undef MEMMAP_ERROR
#elif defined CRC_STOP_SEC_CODE      
  #undef CRC_STOP_SEC_CODE
  #undef MEMMAP_ERROR
#elif defined CRC_START_SEC_CONST_16
  #undef CRC_START_SEC_CONST_16
  #undef MEMMAP_ERROR
#elif defined CRC_STOP_SEC_CONST_16      
  #undef CRC_STOP_SEC_CONST_16
  #undef MEMMAP_ERROR
#elif defined CRC_START_SEC_CONST_32
  #undef CRC_START_SEC_CONST_32
  #undef MEMMAP_ERROR
#elif defined CRC_STOP_SEC_CONST_32      
  #undef CRC_STOP_SEC_CONST_32
  #undef MEMMAP_ERROR
#elif defined CRC_START_SEC_CONST_64
  #undef CRC_START_SEC_CONST_64
  #undef MEMMAP_ERROR
#elif defined CRC_STOP_SEC_CONST_64      
  #undef CRC_STOP_SEC_CONST_64
  #undef MEMMAP_ERROR
#elif defined CRC_START_SEC_CONST_8
  #undef CRC_START_SEC_CONST_8
  #undef MEMMAP_ERROR
#elif defined CRC_STOP_SEC_CONST_8      
  #undef CRC_STOP_SEC_CONST_8
  #undef MEMMAP_ERROR
#elif defined CRC_START_SEC_CODE
  #undef CRC_START_SEC_CODE
  #undef MEMMAP_ERROR
#elif defined CRC_STOP_SEC_CODE      
  #undef CRC_STOP_SEC_CODE
  #undef MEMMAP_ERROR
#endif 
#ifdef MEMMAP_ERROR
#error "Crc_MemMap.h, wrong pragma command" 
#endif
